#!/usr/bin/env python3
"""Generate src/core/psl_data.h from the Mozilla Public Suffix List.

Usage:
    python3 scripts/gen_psl.py [path/to/public_suffix_list.dat] > src/core/psl_data.h

With no argument, downloads the current list from publicsuffix.org.

Emits three sorted string tables (exact rules, wildcard-rule parents, and
exception rules) as offsets into one blob, lowercase ASCII/punycode, ready for
binary search by src/core/psl.c. Both the ICANN and PRIVATE sections are
included — browsers use both for cookie-domain rejection (e.g. github.io).
"""
import sys
import datetime
import urllib.request

URL = "https://publicsuffix.org/list/public_suffix_list.dat"


def to_ascii(rule: str) -> str | None:
    """Punycode a PSL rule (already-ASCII rules pass through)."""
    rule = rule.lower()
    if all(ord(c) < 128 for c in rule):
        return rule
    try:
        import idna  # IDNA2008 + UTS46, what browsers use

        return idna.encode(rule, uts46=True).decode("ascii")
    except Exception:
        try:
            return rule.encode("idna").decode("ascii")  # IDNA2003 fallback
        except Exception:
            print(f"warning: skipping unencodable rule {rule!r}", file=sys.stderr)
            return None


def main() -> None:
    if len(sys.argv) > 1:
        text = open(sys.argv[1], encoding="utf-8").read()
        source = sys.argv[1]
    else:
        text = urllib.request.urlopen(URL).read().decode("utf-8")
        source = URL

    exact, wildcard, exception = set(), set(), set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        if line.startswith("!"):
            r = to_ascii(line[1:])
            if r:
                exception.add(r)
        elif line.startswith("*."):
            r = to_ascii(line[2:])  # store the parent the wildcard hangs off
            if r:
                wildcard.add(r)
        else:
            r = to_ascii(line)
            if r:
                exact.add(r)

    blob = bytearray()
    offsets: dict[str, int] = {}

    def off(rule: str) -> int:
        if rule not in offsets:
            offsets[rule] = len(blob)
            blob.extend(rule.encode("ascii"))
            blob.append(0)
        return offsets[rule]

    tables = {
        "exact": sorted(exact),
        "wildcard": sorted(wildcard),
        "exception": sorted(exception),
    }
    table_offs = {name: [off(r) for r in rules] for name, rules in tables.items()}

    today = datetime.date.today().isoformat()
    print("// Generated by scripts/gen_psl.py — DO NOT EDIT BY HAND.")
    print(f"// Source: {source} ({today})")
    print(
        f"// {len(exact)} exact rules, {len(wildcard)} wildcard parents, "
        f"{len(exception)} exceptions; lowercase ASCII/punycode, each table"
    )
    print("// sorted by strcmp for binary search (see core/psl.c).")
    print("// clang-format off")
    print()

    # Blob as concatenated string literals; rules are [a-z0-9.-] so the only
    # escape needed is the terminating \0, emitted at a literal boundary so it
    # can never be misread as a longer octal escape.
    print("internal const char psl_blob[] =")
    line = "    "
    i = 0
    while i < len(blob):
        end = blob.index(0, i)
        seg = blob[i:end].decode("ascii")
        piece = f'"{seg}\\0"'
        if len(line) + len(piece) > 78:
            print(line)
            line = "    "
        line += piece
        i = end + 1
    print(line + ";")
    print()

    for name in ("exact", "wildcard", "exception"):
        offs = table_offs[name]
        print(f"internal const U32 psl_{name}_off[{len(offs)}] = {{")
        line = "    "
        for o in offs:
            piece = f"{o},"
            if len(line) + len(piece) > 78:
                print(line)
                line = "    "
            line += piece
        print(line)
        print("};")
        print(f"#define PSL_{name.upper()}_COUNT {len(offs)}u")
        print()
    print("// clang-format on")


if __name__ == "__main__":
    main()
